"""empty message

Revision ID: 4ddb9dce8c0e
Revises: 2e6bd753576
Create Date: 2016-05-05 18:41:52.483029

"""

# revision identifiers, used by Alembic.
revision = '4ddb9dce8c0e'
down_revision = '2e6bd753576'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
