"""empty message

Revision ID: 57a6fbac3ada
Revises: 4ddb9dce8c0e
Create Date: 2016-05-12 16:35:38.728303

"""

# revision identifiers, used by Alembic.
revision = '57a6fbac3ada'
down_revision = '4ddb9dce8c0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('add_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'add_date')
    ### end Alembic commands ###
